version: "2"

run:
  timeout: 10m
  modules-download-mode: readonly

formatters:
  enable:
    - gofmt
    - goimports

linters:
  disable-all: true
  enable:
    - errcheck      # Проверяет необработанные ошибки
    - govet         # Стандартный анализатор go vet
    - staticcheck   # Мощный статический анализатор (включает часть gosimple)
    - unused        # Находит неиспользуемый код
    - ineffassign   # Обнаруживает бесполезные присваивания
    - revive        # Замена старого golint

linters-settings:
  goimports:
    local-prefixes: github.com/wantemira/Orders

issues:
  max-issues-per-linter: 0
  max-same-issues: 0