// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "url": "https://github.com/achi3v3",
            "email": "aamir-tutaev@mail.ru"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/link/create": {
            "post": {
                "description": "Create pseudo name for your url-link",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Link"
                ],
                "summary": "Create pseudo link",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL-Link",
                        "name": "origin_link",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/link/delete": {
            "delete": {
                "description": "Delete your struct link on url",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Link"
                ],
                "summary": "Delete link",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL-Link",
                        "name": "origin_link",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/link/get": {
            "get": {
                "description": "Return your struct link on url",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Link"
                ],
                "summary": "Get pseudo link",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL-Link",
                        "name": "origin_link",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/{shortID}}": {
            "get": {
                "description": "Redirect on url",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Link"
                ],
                "summary": "Redirect url 302",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL-Link",
                        "name": "shortID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Swagger PseudoLink API",
	Description:      "Generated API-cellers on server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
